# Generated by Django 2.0.2 on 2023-01-11 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20, null=True)),
                ('que', models.CharField(max_length=650, null=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=50)),
                ('scheme', models.CharField(max_length=20, null=True)),
                ('no_of_ques', models.CharField(max_length=20)),
                ('total_marks', models.CharField(max_length=20)),
                ('time_duration', models.DurationField(default='00:00:00')),
                ('semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounts.Semester')),
                ('stream', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounts.Stream')),
            ],
        ),
        migrations.CreateModel(
            name='FinalScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('registration_number', models.CharField(max_length=20, null=True, unique=True)),
                ('totalmarks', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('question_number', models.PositiveIntegerField(default=1, null=True)),
                ('marks', models.PositiveIntegerField(default=0, null=True)),
                ('question', models.TextField(max_length=500, null=True)),
                ('answer', models.TextField(null=True)),
                ('exam_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exam.Exams')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('registration_number', models.CharField(max_length=20, null=True)),
                ('que', models.CharField(max_length=650, null=True)),
                ('marks', models.FloatField(null=True)),
                ('totalmarks', models.FloatField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='answers',
            name='quest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.Question'),
        ),
        migrations.AddField(
            model_name='answers',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounts.Students'),
        ),
    ]
