# Generated by Django 2.0.2 on 2023-01-11 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StreamName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('user', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('Phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('slug', models.SlugField(max_length=200)),
                ('address', models.TextField(blank=True, max_length=2000, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=200, null=True)),
                ('scheme', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/students/')),
                ('semester', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounts.Semester')),
                ('stream', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounts.Stream')),
            ],
        ),
    ]
